### ISSUE TITLE
Can't compile code generated with bisect_ppx

### ISSUE THREAD

**Issue by KasperJanssens** [aantron/bisect_ppx#151]
When I add bisect_ppx as a dependency, it probably rewrites some code, but I seem to end up with non-compiling code. Worse even, the compiler throws an assertion failed: Fatal error: exception File "typing/typecore.ml", line 2816, characters 15-21: Assertion failed.

The problem seems to appear in a piece of object oriented code, running ocaml 4.03.0+fp+flambda as a compiler. 

Do you have any idea what it might be or where to look? I'll try to look at the generated code but it's kind of large and rather proprietary, so a pointer in the right direction would be helpful, won't be able to post it here.

One of the potential problems I see might be the fact that we also use the lwt extension, but the camlp4 one.

**Comment by aantron** [comment]
This is almost certainly triggered by using Bisect_ppx with Camlp4. I saw the same error (though not sure about the line number at this point) when building some Lwt Camlp4 code with Bisect_ppx enabled.

In general, PPX and Camlp4 are incompatible. This applies even to parsing (Camlp4 AFAIK can't parse PPX): https://github.com/ocaml/camlp4/issues/55. In the case of Bisect_ppx, there is nothing to parse, but using it with Camlp4 still fails with an internal error later.

If at all possible, I recommend switching to the Lwt PPX extension.

It also *might* be possible to adjust Bisect_ppx so that it doesn't have this bad interaction with Camlp4, but we haven't looked into it, and the incompatibility might turn out to be impossible to fix in any reasonable way.

It's possible to use the ancestor of Bisect_ppx, Bisect (OPAM package `bisect`). This has a Camlp4 mode. The home page for that is here: http://bisect.x9c.fr/. It includes a manual.

**Comment by KasperJanssens** [comment]
Jip, moving to the lwt ppx extension (took some time) makes the problem disappear. So most likely you're right, camlp4 and ppx don't play together in this case (we have a ppx extension active where there was no problem between the two, maybe they never had to touch the same lines or so)

**Comment by aantron** [comment]
I'd imagine they don't touch the same file, or maybe the PPX is running first, then the AST is dumped as source for Camlp4 to process. I could be wrong. At least, in 2015, I couldn't get Camlp4 to preprocess any file that had any PPX syntax in it.

Anyway, good to hear it's working, and congrats on moving to the Lwt PPX :)
