### ISSUE TITLE
Bisect not properly escaping filenames?

### ISSUE THREAD

**Issue by Chobbes** [aantron/bisect_ppx#184]
I'm integrating `bisect_ppx` with QuickChick which extracts ocaml code for each test case. One issue right now is that QuickChick makes an ocaml file for each test it runs, and wanting these to be somewhat descriptive, I put the test case in the name. This results in some funny, but perfectly legal characters like spaces winding up in the file names. For instance:

100% /tmp/QuickChick/211642/QuickChick_(choose (0, 10))_d2ec17.ml
 61% /tmp/QuickChick/211853/QuickChick_garbage_choose_cda06f.ml 

Both of these are the exact same test case, however one of them I gave a name without special characters. In the case where the filename has special characters it reports 100% coverage, and clicking on the link shows a blank file. In the other case it behaves as expected.

I'm generating the report with `bisect-ppx-report -I . -html coverage/ bisect*out`

**Comment by aantron** [comment]
@Chobbes, spaces, parentheses, etc., are not valid in OCaml filenames, because the filename is used to generate a module name, and the module name has to be a valid OCaml identifier. In fact, any combination of parentheses, spaces, etc., produces this warning from the compiler:

```
Warning 24: bad source file name: "Foo\(bar\)" is not a valid module name.
```

I suspect you ought to prefer to escape these filenames yourself on account of OCaml, not only of Bisect :)

I wasn't able to reproduce the Bisect part of the problem, however. Bisect seems to handle files named `foo (bar).ml` and `QuickChick_(choose (0, 10))_d2ec17.ml` fine. If this continues to be a problem you think is worth solving, can you provide a minimal project demonstrating the issue (or otherwise help diagnose it? :))

**Comment by Chobbes** [comment]
> @Chobbes, spaces, parentheses, etc., are not valid in OCaml filenames, because the filename is used to generate a module name, and the module name has to be a valid OCaml identifier. In fact, any combination of parentheses, spaces, etc., produces this warning from the compiler:

Ah! OCaml! That's a good point, I totally forgot about that.

I've gotten around this problem for now by removing the characters that were causing problems. Strange that it works for you and not me --- when I remove the special characters it starts working. Must be something in the file.

Anyway, thanks! You raise good points :).
