### ISSUE TITLE
ppx_let blocking instrumentation

### ISSUE THREAD

**Issue by briancaine** [aantron/bisect_ppx#186]
I'm using bisect_ppx (1.4.0), ppx_let (v0.11.0), ocaml compiler 4.04.1 with dune (1.6.3).

The `let%bind` syntax seems to be blocking instrumentation in the function past its first occurrence.

This is my source file:
```ocaml
module Let_syntax = struct

  let bind ~f = function
    | Some value -> f value
    | None       -> None

end

let opt_add_one ?some_var () =
  let%bind some_var = some_var in
  Printf.printf "opt_add_one: %d is %s\n" some_var (if some_var mod 2 = 0 then "even" else "odd");
  Some (some_var + 1)

(*
let opt_add_one ?some_var () =
  Let_syntax.bind
    some_var
    ~f:(fun some_var ->
        Printf.printf "opt_add_one: %d is %s\n" some_var (if some_var mod 2 = 0 then "even" else "odd");
        Some (some_var + 1))
 *)

let main () =
  (match opt_add_one () with
   | None       -> Printf.printf "main 1: None\n"
   | Some value -> Printf.printf "main 1: Some %d\n" value);

  match opt_add_one ~some_var:5 () with
  | None       -> Printf.printf "main 2: None\n"
  | Some value -> Printf.printf "main 2: Some %d\n" value

let () = main ()
```

This is my dune file:
```lisp
(executable
 (name       my_file)
 (preprocess (pps bisect_ppx -conditional ppx_let))
 (modules    my_file))
```

My makefile:
```Makefile
coverage :
	rm -rf `find . -name 'bisect*.out'` _coverage
	BISECT_ENABLE=YES dune build my_file.exe
	dune exec ./my_file.exe
	bisect-ppx-report -I _build/default/ -html _coverage/ `find . -name 'bisect*.out'`
```

This is what the coverage report looks like:
![incomplete_coverage](https://user-images.githubusercontent.com/1744393/51963567-102f2280-2432-11e9-8152-a9515343b603.png)

I just kinda threw anything I could at the wall to see if there was an easy fix. I tried shuffling around the order of the preprocessors in the dune file, as well as trying dune's [`staged_pps` preprocessing](https://jbuilder.readthedocs.io/en/latest/dune-files.html#preprocessing-specification).

None of them worked, but they also didn't break the build either.

Is this a bug or am I missing something obvious?

**Comment by aantron** [comment]
Looking into it.

**Comment by aantron** [comment]
Also, @rgrinberg, do you know why changing the order of PPXs in the `dune` file doesn't seem to cause `ppx_let` to run first? I (and I guess @briancaine) tried with

```scheme
(executable
 (name       my_file)
 (preprocess (pps ppx_let bisect_ppx -conditional))
 (modules    my_file))
```

but showing the AST observed by Bisect shows that it is still untransformed by ppx_let when Bisect is invoked.

**Comment by Drup** [comment]
> @Drup, @hcarty, @sgrove, @andreas, @jaredly, @andreypopp, can you think of any other PPXs that use expressions with extension points (`keyword%extension`), and the payload should not be instrumented?

All the one that define some kind of DSL .... so a lot of them. 

I think the real solution to this problem is just yell very loudly at the user when encountering an extension, and tell him to place bisect last. I don't know how this ordering is done in dune/omp.

Regarding the pertinence of bisect's instrumentation, one solution is to make bisect_ppx recognize annotations (`[@bisect.ignore]` ?) that ppx could leave lying around. Merlin has similar annotations. But those annotations should only be a refinement.

**Comment by aantron** [comment]
If Bisect runs last, I agree with adding a warning when extensions are encountered.

If Bisect runs first, I'm leaning towards giving Bisect a command-line option like `-instrument-extensions bind,map`, and Bisect will recursively instrument only extensions that are in that whitelist. We can make a default whitelist. Extending it later will be a breaking change, but probably not very disruptive, because Bisect is used only during development, not for production.

One additional point in favor of running last is that we can appear to instrument DSLs, if extensions put meaningful locations into the code that they generate.

**Comment by jaredly** [comment]
yeah I'd +1 to always having Bisect_ppx run last. Seems like the most predictable behavior.

**Comment by rgrinberg** [comment]
@aantron bisect_ppx should handle ordering via the omp API:

```
(** Register a ppx rewriter. [position] is a integer that indicates
    when the ppx rewriter should be applied. It is guaranteed that if
    two ppx rewriters [a] and [b] have different position numbers, then
    the one with the lowest number will be applied first. The rewriting
    order of ppx rewriters with the same position number is not
    specified. The default position is [0].

    Note that more different position numbers means more AST
    conversions and slower rewriting, so think twice before setting
    [position] to a non-zero number.
*)
val register
  :  name:string
  -> ?reset_args:(unit -> unit) -> ?args:(Arg.key * Arg.spec * Arg.doc) list
  -> ?position:int
  -> 'types ocaml_version -> 'types rewriter
  -> unit
```

Setting `position` to something `> 0` should do the job.

**Comment by aantron** [comment]
Thanks @rgrinberg, I wasn't aware that had been added. It fixes this issue.
