### ISSUE TITLE
how should the test be run?

### ISSUE THREAD

**Issue by gasche** [aantron/bisect_ppx#197]
While I was investigating a testsuite failure for bisect_ppx.{1.3.1,1.3.2} under OCaml 4.08, I noticed that with the following test instructions

```
dune build -p bisect_ppx
dune runtest -p bisect_ppx
```

it seems that the `runtest` command does nothing at all on 1.3.3 and more recent versions (I just checked on master). Is this a bug, or is there a different test command?

(You would think of using `make test`, but unfortunately I cannot really because this seems to use (on recent `dune` version) the `dev` profile which breaks the build under 4.08 due to new deprecation warnings enabled as errors.)

**Comment by gasche** [comment]
For opam-repository context, see

https://github.com/ocaml/opam-repository/pull/14464
https://github.com/gasche/opam-repository/commit/f9bdef51f0b5e48061a82c0f0eaaf9bf40aa0dbf
https://github.com/gasche/opam-repository/commit/0f4abc130bf8a60e1e9a9806a824e13cf79a3e6b

**Comment by aantron** [comment]
I disabled `runtest` in favor of manually running the tests in 73bb99edd14e57bc4b471ff0e89ddff369d09d77, because back then Jbuilder wouldn't rerun the tests on `make test` if the tester hadn't changed. This was a problem, because the tester does not directly depend on `src/`, so Bisect_ppx could change, and not force a rerun of the tests.

`--force` was added to Jbuilder after that, and has been present in every release of Dune, so I'll revert that commit.

**Comment by gasche** [comment]
Sounds nice, thanks! Note that I still expect issues with tests on 4.08, similar to 

  https://github.com/mirage/ocaml-cstruct/issues/263

(plus a bunch of `Pervasives` deprecation warnigns)

**Comment by gasche** [comment]
(Unlike the `ppx_cstruct` case you control the test runner so you should easily be able to use `-error-style short` conditionally or pass `OCAML_ERROR_STYLE=short` to the compiler invocatoin.)

**Comment by aantron** [comment]
The commit linked above makes `runtest` work again. The 4.08 issues may have been fixed in 78486280848c8d16eeb4dacd7425643df4c09287 and 525ceb2fb9a16d1e252d22408d3e6c62b80785b1, which are in `master`, but not released. I have Bisect_ppx passing its own tests with `runtest` locally on 4.08. Should I restore the `with-test` line in opam, and make a new release? Note that these changes don't affect the production release, as `Pervasives` deprecation is a warning, and the error formatting difference only affects the test suite.

**Comment by gasche** [comment]
That looks fine to me. The fact of just disabling tests under 4.08 and newer versions is a bit of a cop-out -- it will not remain a robust solution until you are willing to drop pre-4.08 support and flip the switch -- hopefully you will find a more robust solution later.

**Comment by aantron** [comment]
If that's in reference to 78486280848c8d16eeb4dacd7425643df4c09287, I'll try `OCAML_ERROR_STYLE=short`, which I wasn't previously aware of. Thanks.

**Comment by gasche** [comment]
Nice fix, thanks!
