### ISSUE TITLE
Submitting coverage reports to Codecov?

### ISSUE THREAD

**Issue by DilumAluthge** [aantron/bisect_ppx#226]
I noticed that Bisect_ppx has support for submitting coverage reports to Coveralls.

Is there any way to submit coverage reports from Bisect_ppx to Codecov (https://codecov.io)?

**Comment by aantron** [comment]
Not yet. Looking through [these docs](https://docs.codecov.io/docs/supported-languages), I don't see explicit support for OCaml yet. [This](https://github.com/codecov/codecov-bash/blob/master/codecov) seems to be their upload script, to either contribute to or reverse-engineer.

I'm looking through other languages' sample repos, such as [for Rust](https://github.com/codecov/example-rust).

**Comment by aantron** [comment]
I see [this line](https://github.com/codecov/codecov-bash/blob/1044b7a243e0ea0c05ed43c2acd8b7bb7cef340c/codecov#L1044) in the Codecov bash script, in their file search pattern:

```bash
-or -name 'excoveralls.json' \
```

I suggest first trying to follow the instructions for [Coveralls](https://github.com/aantron/bisect_ppx#sending-to-coveralls), but renaming the output file to `excoveralls.json`, and replacing the `curl` command by `bash <(curl -s https://codecov.io/bash)`. It might work :)

Please let me know if it works or not. If it does, I'll update the instructions.

Note that if you have a release version of Bisect_ppx installed, the reporter options are prefixed with one dash, so `-coveralls` instead of `--coveralls`, etc.

**Comment by aantron** [comment]
The suggestion works indeed, here's an example: https://codecov.io/gh/aantron/bisect-ci-integration-megatest/src/master/simple.ml

The commands were:

```
bisect-ppx-report \
  --coveralls excoveralls.json \
  --service-name travis-ci --service-job-id $TRAVIS_JOB_ID \
  bisect*.out
bash <(curl -s https://codecov.io/bash)
```

Codecov's script displayed [this](https://travis-ci.org/aantron/bisect-ci-integration-megatest/builds/576558354#L226).

This is with Bisect_ppx `master`.

I created a [repo](https://github.com/aantron/bisect-ci-integration-megatest) for testing all possible integrations (between reasonably popular services). It will have a nice README eventually. It's tracked in #227. I'll only implement a subset of the integrations in that issue at first.

I'm also planning to simplify the reporter command line until you can send coverage to Codecov with just

```
bisect-ppx-report --send codecov
```

from any CI, because we can detect the CI (#228) and issue the right command from the reporter (#233). That's not implemented yet, but I will work on it once I know how the integrations between enough services work. It will be part of the next release.

I'm closing this issue in favor of tracking Codecov integration in #227. Please comment/reopen if still having trouble!

**Comment by aantron** [comment]
`master` now has `bisect-ppx-report --send-to Codecov`, which works at least [in Travis](https://github.com/aantron/bisect-ci-integration-megatest/blob/1729d30cf4365b6b6da2b10ee9c0df80e4ac5de7/.travis.yml#L25).
