### ISSUE TITLE
Compatibility issues with (copy_files) stanza in dune

### ISSUE THREAD

**Issue by bandersongit** [aantron/bisect_ppx#263]
Bisect_ppx is crashing when generating coverage for files that are include via the dune (copy_files) stanza with the following message

```
Info: found coverage files in './'
 *** system error: src/console/ObjectPrinter.re: No such file or directory
```

The literal error makes sense because there is no file at that location.

This is reproducible here https://github.com/facebookexperimental/reason-native/tree/bisect_ppx-copy_files-issue

**Comment by aantron** [comment]
Ok, sorry for the delay. I reproduced this locally with a simpler project, but not using esy.

By default, Bisect_ppx `master` searches for source files in `.` and `./_build/default`:

https://github.com/aantron/bisect_ppx/blob/02dfb10188033a26d07d23480c2bc44a3a670357/src/report/report.ml#L52

`./_build/default` is usually enough to handle `copy_files`, since Dune copies the source file to its effective location inside `_build/default`.

The error you are seeing is most likely caused by either using a Dune workspace, or by esy building the project somewhere other than in `_build`. If the latter, you can probably fix it by adding `buildsInSource` to `esy.json`:

https://github.com/aantron/bisect_ppx/blob/02dfb10188033a26d07d23480c2bc44a3a670357/esy.json#L34-L38

Otherwise, you have to specify the location of the build source tree to `bisect-ppx-report` with `-I`:

```
       -I DIRECTORY
           Directory in which to look for source files. This option can be
           specified multiple times. File paths are concatenated with each -I
           directory when looking for files. The default directories are ./
           and ./_build/default/
```

In any case, the error message needs to be improved.

**Comment by aantron** [comment]
It may also be possible to better integrate Bisect_ppx with esy here, so it automatically "knows" the build directory, but I haven't looked into it yet. If not, a note about `buildsInSource` should be added to the Bisect_ppx docs.
