### ISSUE TITLE
Error with redefined || operator

### ISSUE THREAD

**Issue by bbc2** [aantron/bisect_ppx#306]
I have an error when I try to instrument the following example (`foo.ml`) with bisect_ppx:

```ocaml
let (||) = (^)

let () = print_endline ("Hello, " || "World!")
```

```
BISECT_ENABLE=yes dune exec ./foo.exe
File "foo.ml", line 3, characters 24-33:
3 | let () = print_endline ("Hello, " || "World!")
                            ^^^^^^^^^
Error: This expression has type string but an expression was expected of type
         bool
       because it is in the condition of an if-statement
```

* bisect_ppx 2.2.0
* Dune 2.4.0
* OCaml 4.08.1

**Comment by aantron** [comment]
Bisect has special handling for `||`, due to its short-circuiting behavior, which has implications for coverage (the same as `if`). It actually rewrites `||` to an `if` expression:

https://github.com/aantron/bisect_ppx/blob/017e6addb1d4a25bade8917004a136915807fdca/src/ppx/instrument.ml#L1029-L1047

Would it be a reasonable request not to redefine `||`?

If not, perhaps we can add an attribute or a PPX option to suppress special handling. If this is in the public API of a library, I'm not sure what is better.

I also see a typo in the code I just linked, so I will fix that now...

**Comment by aantron** [comment]
Closing this for now.
