### ISSUE TITLE
How to exclude "node_modules" in BuckleScript/Jest project?

### ISSUE THREAD

**Issue by jihchi** [aantron/bisect_ppx#309]
Hi and thanks for the great tool!

I'm working on this [the draft](https://github.com/reazen/relude/pull/261), trying to switch to bisect ppx from Jest. I am able to generate code coverage report, but [the report](https://coveralls.io/builds/30172931) includes a 3rd-party library:

![reazenrelude  Build #165  Coveralls - Test Coverage History   Statistics 2020-04-19 16-21-23(1)](https://user-images.githubusercontent.com/87983/79683069-0291d280-825a-11ea-83c9-1d6ec7fe1b96.jpg)

I'm wondering how to exclude 3rd-party libraries under `node_modules` folder?

**Comment by aantron** [comment]
@jihchi  `node_modules` is actually already excluded, because BuckleScript doesn't apply your `bsconfig.json` to any of the code that's from a third-party module, in particular, it doesn't apply your project's `ppx-flags` to `node_modules/bs-bastet`.

What's happening is that bs-bastet itself also [uses Bisect_ppx](https://github.com/Risto-Stevcev/bastet/blob/479230c466de4c13df41876fe2f4484cfd4d25fa/bsconfig.json#L36), so it's also getting instrumented when you run with `BISECT_ENABLE=yes`. https://github.com/BuckleScript/bucklescript/issues/3761 will add dev-only `ppx-flags`, which will allow bs-bastet (and relude) to automatically not depend on Bisect at all when they are installed as third-party packages.

I understood from @bobzhang that https://github.com/BuckleScript/bucklescript/issues/3761 will be included in the next release of BuckleScript (7.4?), so I suggest we wait until then, instead of trying to implement some workaround.

(Note that we need dev-only `ppx-flags` apart from any workaround we could implement in Bisect, because we want to make sure that released packages never even try to call Bisect, and thus don't depend on it being installed at all).

Also cc @Risto-Stevcev.

**Comment by aantron** [comment]
Going to close this for now, as it is tracked in BuckleScript.
