### ISSUE TITLE
Reporter: behave better with esy "buildsInSource": "_build"

### ISSUE THREAD

**Issue by davesnx** [aantron/bisect_ppx#328]
Hey @aantron, first of all thanks for this tool!

I wanted to integrate in [query-json](https://github.com/davesnx/query-json) with esy and dune running on Github Actions and I'm running into problems.

I'm working on this PR, https://github.com/davesnx/query-json/pull/18 (just in case you want to check or repro).

In the ci is where it runs tests with BISECT_ENABLE=yes and the *.coverage appears to get generated (https://github.com/davesnx/query-json/pull/18/checks?check_run_id=1140986426#step:11:31) but later the `bisect-ppx-report send-to` doesn't seem that it read its correctly and crashes: https://github.com/davesnx/query-json/pull/18/checks?check_run_id=1140986426#step:11:51

I'm missing something or there's a bug on here?

Thanks for your help and let me know if you need more info.

**Comment by aantron** [comment]
This is most likely being caused by the report tool detecting that you are running in esy and trying to search the sandbox for `*.coverage` files:

https://github.com/aantron/bisect_ppx/blob/a4b8cb617dd9b8f33be8da7b8e63390e81b85fb6/src/report/report.ml#L306-L310

however, you are using `"buildsInSource": "_build"` and running things from the current directory (the latter part I onlu presume). I don't know if that's enough to cause esy to set the environment variable that the reporter is checking, yet not create the directory, or remove it after the build command runs, but this is my hypothesis.

Bisect_ppx should either detect `"buildsInSource": "_build"` or automatically try to use a fallback that will work in this case, which is probably just to try the regular Dune project paths.

You should be able to work around this immediately by specifying the `*.coverage` files on the command line with either `*.coverage` (the ordinary shell glob) or `--coverage-path .`. This will suppress the reporter trying to detect the project layout and do an automatic search.

**Comment by davesnx** [comment]
Worked perfectly. Using the glob, the coverage-path flag seems isn't available.

It would be nice to see more info with verbose which directory the tool is working on, aside from that worked great.

Thanks for this.

**Comment by aantron** [comment]
Thanks @davesnx :) I'm going to reopen this issue, and make it about improving the verbose output. Perhaps also about investigating looking in `./_build` as a fallback under esy, to handle the most common `buildsInSource` setup.

**Comment by aantron** [comment]
The linked commit should fix the original issue. As it turns out, the report tool already wanted to search the current directory and `_build` for `*.coverage` files. When `cur__target_dir` was defined by esy, it would also try to search in the directory given by that environment variable. However, that directory would not exist in case `"buildsInSource"` was used, and the reporter would fail. The commit makes the reporter check for the existence of the directory in `cur__target_dir` before searching it (as it already checks for the existence of `_build`).
