### ISSUE TITLE
Assertion error when (&&) is partially applied

### ISSUE THREAD

**Issue by keleshev** [aantron/bisect_ppx#333]
I encountered assertion error when preprocessing code like `((&&) foo)`. Looks like bisect_ppx assumes that `&&` (and friends) always take two parameters:

https://github.com/aantron/bisect_ppx/blob/a4b8cb617dd9b8f33be8da7b8e63390e81b85fb6/src/ppx/instrument.ml#L1061-L1072

**Comment by aantron** [comment]
I'll fix this shortly so that it only matches when there are two arguments. Currently I'm in the middle of some build/test problems triggered by porting to Dune 2.7, so I'll do this issue afterwards and include it in the release.

In the meantime, you should be able to work around it by tagging the surrounding expression with `[@coverage off]`. That should suppress traversal of that part of the AST.

**Comment by keleshev** [comment]
No worries, @aantron, we had `(&&)` partially applied only in a few places and we simply eta-expanded them now.

**Comment by aantron** [comment]
The linked commit adds a test for this, and fixes it. Thanks for the report!
