### ISSUE TITLE
Utility to merge coverage files

### ISSUE THREAD

**Issue by vch9** [aantron/bisect_ppx#388]
In our CI we upload several coverage files as artifacts (to create a unified report at the end). However, there is a __lot__ of coverage files and it's too heavy for the CI.

An utility like `bisect-ppx-report merge` could merge every `.coverage` file?

If you agree with this feature, I'd be happy to implement this.

**Comment by aantron** [comment]
Yes, I'll be happy to review and... *merge* it.

I am understanding it as effectively a "report" output format in which a merged `.coverage` file is the output.

**Comment by vch9** [comment]
Cool :)!
I just started this morning to work on this. In contrast of my last merge request, I'd like to add some tests for this new report. However, I'm not sure to understand the testing suite, If i want to add tests for source files (no call to `bisect-ppx-report` but rather call to `Report*.output`), where should I put these tests ?

**Comment by aantron** [comment]
You should be able to write cram tests for `merge`, as [here](https://github.com/aantron/bisect_ppx/tree/master/test/report). Since the recent refactoring, the `.coverage` format is basically ASCII so it should be easy to dump it. Even if it wasn't, however, you could always use `hexdump -C`.

> My bad, this is an executable I can not have access to `Report*.output`, I think I will have the `merge` function in `Bisect_common` as it will be easier to test such a function

Please don't add it in `Bisect_common`. It doesn't belong there, but in some `src/report/merge.ml` file. Putting it in `Bisect_common` will greatly complicate reading the code, since it will unnecessarily increase the set of functions that might be used by the runtime, PPX, and all reporters, from a reader's point of view.

**Comment by vch9** [comment]
> You should be able to write cram tests for `merge`, as [here](https://github.com/aantron/bisect_ppx/tree/master/test/report). Since the recent refactoring, the `.coverage` format is basically ASCII so it should be easy to dump it. Even if it wasn't, however, you could always use `hexdump -C`.

I will do that yes thank you.

> Please don't add it in `Bisect_common`. It doesn't belong there, but in some `src/report/merge.ml` file. Putting it in `Bisect_common` will greatly complicate reading the code, since it will unnecessarily increase the set of functions that might be used by the runtime, PPX, and all reporters, from a reader's point of view.

I usually like to keep utilities functions close to the type declaration, I believe they can be omitted while reading the code as the reader would just ignore as he does not need such utility. But, I do understand the common place of `Bisect_common` and the want to _not_ increase the set of functions. I will keep this in `src/report/merge.ml`
