### ISSUE TITLE
Compare coverages

### ISSUE THREAD

**Issue by vch9** [aantron/bisect_ppx#392]
In our project we have several testing frameworks. Our goal is to unify the framework, and thus, we are migrating every tests to a single one framework. However, we do this step by step and we want to ensure ourselves that we cover at least the exact same lines.

I would like to have in the following configuration:
```ocaml
(* foo.ml *)
1  let f () =
2    ..               (* Covered by B *)
3  let g () =
4    ..               (* Covered by A & B *)
5  let h () =
6    ..               (* Covered by A *)
7  let i () =
8    ..               (* Not covered *)
```

Then, I would produce a specific html report:
```
Line 2:  B adds new coverage, the line is colored with a color X
Line 4:  Everything is fine, the line is colored with a color Y
Line 6:  We lose coverage, the line is colored with a color Z
Line 8:  No color
```

This is a very specific need, I plan on implementing this myself using the bisect framework or not. Let me know if that something you think would be appropriate for this project :)

**Comment by aantron** [comment]
Bisect formerly could do arithmetic on `.coverage` files with "combine expressions."

Essentially, `bisect-ppx-report merge` that you implemented in #389 is sum (since Bisect_ppx inherently does a sum when loading multiple `.coverage` files). In the past, `bisect-ppx-report` also could do difference, but I removed it in https://github.com/aantron/bisect_ppx/issues/105 because it was complicating the reporter and we could find no users.

It looks like the information you want to get can be somewhat awkwardly obtained by computing differences again, and maybe also replacing numbers greater than 1 by 1, which should be easier with today's refactored reporter. You could then subtract reports generated with the new testing framework from the old, and locations marked in green would be those covered in the old framework, but not the new.

To get the exact presentation you want looks like it would need changing or generalizing the points so that instead of being a map from point to visitation count (an `int)`, they would be a map from point to some more complex data structure (or encode that data structure in an `int`), and also changing the HTML generator (or other) to be able to display that. I'm not at first glance sure doing it that way is worth it in Bisect_ppx.

**Comment by aantron** [comment]
If the first approach (normalizing all counts to 0 or 1, and subtracting the new suite's coverage from the old) is good enough, I suggest to add something like a `--set-minus` argument as a common option to all reporters. It would take either a single `.coverage` file or a directory to recursively scan for `.coverage` files, and could be given multiple times.

The reporters would load coverage as normal, but, if `--set-minus` is present at least once, separately load and sum all the `--set-minus` `.coverage` files, squash all positive counts to 1, and subtract the `--set-minus` `.coverage` files from the basic report. And then just continue rendering as now.

**Comment by vch9** [comment]
> To get the exact presentation you want looks like it would need changing or generalizing the points so that instead of being a map from point to visitation count (an int), they would be a map from point to some more complex data structure (or encode that data structure in an int), and also changing the HTML generator (or other) to be able to display that

This would be closer to what I will favor. In a ideal world, the user (us), could quickly identify differences between the two reports, with also helpers like "list files in decreasing order of `We lose coverage`"

> I'm not at first glance sure doing it that way is worth it in Bisect_ppx.

I think too, it is really specific to our need (I hope no one else spends his time switching from one testing framework to another). I'm aware this would pollute the project the way I picture it. It's not essential at all for bisect I believe and can live on my tweaked fork for a while.

**Comment by aantron** [comment]
I'm closing this issue. It's just so that I don't have to rethink it each time I look at it, since I think there is nothing to do in Bisect on it for now. But if you have any more comments, please do comment and/or reopen it :)
