### ISSUE TITLE
Semantic of `Lazy.is_val` changes using `bisect_ppx`

### ISSUE THREAD

**Issue by Ngoguey42** [aantron/bisect_ppx#398]
When `dune` and `main.ml` contain: 
```
(executable (name main) (instrumentation (backend bisect_ppx)))
```

```ocaml
let () =
  let v = lazy 42 in
  Printf.printf "%b\n" (Lazy.is_val v);
  let v = Lazy.from_val 42 in
  Printf.printf "%b\n" (Lazy.is_val v)
```

`dune exec bisect_ppx -- ./main.exe` produces:
```
true
true
```

while `dune exec --instrument-with bisect_ppx -- ./main.exe` produces:
```
false
true
```

```
$ dune --version; ocaml --version; opam show bisect
2.9.0
The OCaml toplevel, version 4.11.1
version       1.3.1
```

**Comment by aantron** [comment]
It appears that `lazy` creates already-forced values for:

- `int`, `float`, `string`, `bool`, `char`, `unit`.
- Zero-argument non-polymorphic constructors, including `[]`, and zero-argument constructors of extensible variant types, including `exn`.
- Functions.

Bisect_ppx can't detect these in general, however, because `lazy` examines the run-time representation, i.e. this "optimization" is applied even in case of

```ocaml
let x = 42 in
let y = lazy x in
Lazy.is_val y (* true *)
```

...and also holds even if `x` is abstract and cannot be examined syntactically at all.

It seems like the only way to get fully consistent behavior is not to instrument immediately inside `lazy` at all. If the nested expression is complex enough, it will have its own instrumentation anyway (and not be a value). However, there are some syntactic values, that are not considered forced immediately, such as `Some ()`:

```ocaml
let x = lazy (Some ()) in
Lazy.is_val x (* false *)
```

Bisect would no longer instrument inside these `lazy` expressions at all, even though it is safe to do so, and it might be interesting to know if they are ever forced. I'll take a more exhaustive look at the expressions affected by not instrumenting right under `lazy`, and decide whether to make the change.

**Comment by aantron** [comment]
Actually, it's likely syntactic, and it's not the run-time representation that's being examined, but this is decided by the lazy compilation scheme:

```ocaml
# let x = Some ();;
val x : unit option = Some ()
# lazy x;;
- : unit option lazy_t = lazy (Some ())
# lazy (Some ());;
- : unit option lazy_t = <lazy>
```

That suggests Bisect can do the right thing by examining the subexpression.

**Comment by aantron** [comment]
Should be fixed in `master` now, and will be included in the next release. Thanks for reporting!
