### ISSUE TITLE
Evaluate expression propogation 

### ISSUE THREAD

**Issue by rleonid** [aantron/bisect_ppx#60]
for "or" expansion.

**Comment by aantron** [comment]
@rleonid, what do you say we close this? I'm under the impression that we've agreed in conversations elsewhere that the way Bisect handles or-patterns is right (among the two alternatives discussed in https://github.com/aantron/bisect_ppx/issues/43, at least).

**Comment by rleonid** [comment]
I don't recall the convincing reason but I do remember the conversation!

**Comment by aantron** [comment]
Thanks. I also don't remember the details right now, but the high-level structure of the history of this was:

- You originally proposed a correct method for handling or-patterns, which is what was implemented.
- I originally proposed an incorrect method, and this issue was about evaluating that incorrect method.

So thanks :) The reason for why this is incorrect is, IIRC, also written somewhere in #43 or the PR that closed it.
