### ISSUE TITLE
Avoid -dsource in testing

### ISSUE THREAD

**Issue by aantron** [aantron/bisect_ppx#91]
At present, automatically testing for both 4.02 and 4.03 is impractical, because the testing framework uses diffs on `-dsource` output. The formatting has changed between 4.02 and 4.03. Perhaps the comparison method should be changed to some kind of structural parse tree comparison, with `-dsource` output printed only in case of error.

**Comment by rleonid** [comment]
As a stop gap, have you thought about having 2 different versions of `-dsource` formatted output? 

Even the "right" testing framework of comparing actual `AST`'s is problematic; because those structures are also version specific. This seems like a tough problem to solve elegantly. In my opinion, the test suite is more useful to prevent regression tests, having hard coded files to compare against, for this reason seems reasonable.

**Comment by aantron** [comment]
Yeah, I first considered having two versions. It would work, but it seems like a bit of a pain to maintain.

What I thought of doing to avoid version-specificity in ASTs is to have the reference files in source form, as now, but then to parse them, and compare against the resulting trees. Obviously, this makes the testing framework somewhat complicated, so I'd rather think of something better... or just go with the stop gap suggestion :)
